Metrics/BlockLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 120

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
