language: ruby
dist: xenial

matrix:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

branches:
  only:
    - master

cache:
  bundler: true

before_install:
  - gem update --system
  - gem update --no-document
  - gem cleanup

script:
  - bundle exec rake test
  - bundle exec rake scss_lint
