name: GitHub Actions CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.4, 2.5, 2.6, 2.7]
    steps:
    - name: Checkout sources
      uses: actions/checkout@master
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock', '**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install gems
      run: |
        echo "gem: --no-document" > ~/.gemrc
        gem install -N bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        gem cleanup
    - name: Test Ruby
      run: bundle exec rake rubocop
    - name: Test SCSS
      run: bundle exec rake scss_lint
    - name: Run tests
      run: bundle exec rake test
